version: '3'

tasks:
  build:
    desc: "Build the Go applications"
    cmds:
      - mkdir -p build
      - go build -v -o build/mcp-server ./cmd/mcp-server
      - go build -v -o build/sync-job ./cmd/sync-job
      - go build -v -o build/migrate ./cmd/migrate

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  fmt:
    desc: "Format all Go files"
    cmds:
      - go fmt ./...

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy
